### ISSUE TITLE
This repository is behind docker hub, please commit the latest version.

### ISSUE THREAD

**Issue by dpmabo** [bloXroute-Labs/gateway#5]
Latest version on docker hub is 2.109.10. 
But the latest version of this repository is 2.108.3.
Please fix this issue. Thanks.

[v2.109.10]
(https://hub.docker.com/layers/bloxroute/bloxroute-gateway-go/v2.109.10/images/sha256-58b38d84d4f62008ace132a9443eba408b8549ba7e23ca00c764d547efa9d88a?context=explore)

**Comment by Uri-Margalit-bloXroute** [comment]
we released the latest version v2.115.2
