### ISSUE TITLE
failed to send tx receipt for 55b31dc74615cbf513bd252782ac4e41454a16973ddfc41f880409ecbe1475fc

### ISSUE THREAD

**Issue by hebeillc** [bloXroute-Labs/gateway#6]
Hi, I run local gateway, Sometimes will report an error:"failed to send tx receipt for 55b31dc74615cbf513bd252782ac4e41454a16973ddfc41f880409ecbe1475fc"

I run the gateway use "sudo docker run --name bxgateway-go -d -v /home/ubuntu/gateway_log:/app/bloxroute/logs -v /home/ubuntu/ssl:/app/bloxroute/ssl -p 1801:1801 -p 28333:28333 bloxroute/bloxroute-gateway-go --blockchain-network BSC-Mainnet --ws --port 1801 --private-key xxxxxxx --enodes enode://xxxxxxx@x.x.x.x:30311 --eth-ws-uri ws://x.x.x.x:8546 --txtrace"

Does anyone know why？ Tanks!

**Comment by vitalii427** [comment]
We don't use github for customer support. Please post a message on [our Discord](https://discord.gg/jHgpN8b) server.
